Repository woorifisa-projects-3rd/woori-zip-BE, pull requests merged in 2024-11, with the labels that each got.

#8 [SETTING] DB 업데이트
  README.md
  src/main/java/fisa/woorizip/backend/facility/domain/Facility.java
  src/main/java/fisa/woorizip/backend/house/domain/House.java
  src/main/java/fisa/woorizip/backend/loanchecklist/LoanCheckListErrorCode.java
  src/main/java/fisa/woorizip/backend/loanchecklist/controller/LoanCheckListController.java
  src/main/java/fisa/woorizip/backend/loanchecklist/domain/LoanCheckList.java
  src/main/java/fisa/woorizip/backend/loanchecklist/repository/LoanCheckListRepository.java
  src/main/java/fisa/woorizip/backend/loanchecklist/service/LoanCheckListService.java
  src/main/java/fisa/woorizip/backend/loanchecklist/service/LoanCheckListServiceImpl.java
  src/main/java/fisa/woorizip/backend/loangoods/domain/LoanGoods.java
  src/main/java/fisa/woorizip/backend/log/LogErrorCode.java
  src/main/java/fisa/woorizip/backend/log/controller/LogController.java
  src/main/java/fisa/woorizip/backend/log/domain/Log.java
  src/main/java/fisa/woorizip/backend/log/repository/LogRepository.java
  src/main/java/fisa/woorizip/backend/log/service/LogService.java
  src/main/java/fisa/woorizip/backend/log/service/LogServiceImpl.java
  src/main/java/fisa/woorizip/backend/member/domain/EarningsType.java
  src/main/java/fisa/woorizip/backend/member/domain/Member.java
  src/main/java/fisa/woorizip/backend/member/domain/Role.java
  src/main/java/fisa/woorizip/backend/recentlyloangoods/RecentlyLoanGoodsErrorCode.java
  src/main/java/fisa/woorizip/backend/recentlyloangoods/controller/RecentlyLoanGoodsController.java
  src/main/java/fisa/woorizip/backend/recentlyloangoods/domain/RecentlyLoanGoods.java
  src/main/java/fisa/woorizip/backend/recentlyloangoods/repository/RecentlyLoanGoodsRepository.java
  src/main/java/fisa/woorizip/backend/recentlyloangoods/service/RecentlyLoanGoodsService.java
  src/main/java/fisa/woorizip/backend/recentlyloangoods/service/RecentlyLoanGoodsServiceImpl.java
  src/main/resources/db/migration/V1__init.sql
Labels: ⚙ Setting

#13 [SETTING] CI/CD 구축
  .github/workflows/ci.cd.prod.yml
  .github/workflows/ci.cd.test.yml
  .gitignore
  README.md
  appspec.yml
  build.gradle
  scripts/after-deploy.sh
  scripts/start-server.sh
  scripts/stop-server.sh
Labels: ⚙ Setting

#15 [SETTING] CI/CD 코드 변경
  .github/workflows/ci.cd.test.yml
Labels: ⚙ Setting, 🌏 Deploy

#16 [SETTING] CI/CD 코드 변경
  .github/workflows/ci.cd.test.yml
  build.gradle
  src/main/java/fisa/woorizip/backend/common/exception/GlobalExceptionHandler.java
  src/main/java/fisa/woorizip/backend/common/exception/errorcode/CommonErrorCode.java
  src/main/java/fisa/woorizip/backend/common/exception/response/ErrorResponse.java
  src/main/java/fisa/woorizip/backend/member/MemberErrorCode.java
  src/main/java/fisa/woorizip/backend/member/controller/MemberController.java
  src/main/java/fisa/woorizip/backend/member/domain/EarningsType.java
  src/main/java/fisa/woorizip/backend/member/dto/request/SignUpRequest.java
  src/main/java/fisa/woorizip/backend/member/service/MemberService.java
  src/main/java/fisa/woorizip/backend/member/service/MemberServiceImpl.java
Labels: ⚙ Setting

#17 [FEAT] 로그인, 로그아웃 - 토큰 관리 (중간 병합)
  build.gradle
  src/main/java/fisa/woorizip/backend/common/config/AuthConfig.java
  src/main/java/fisa/woorizip/backend/member/AuthErrorCode.java
  src/main/java/fisa/woorizip/backend/member/MemberErrorCode.java
  src/main/java/fisa/woorizip/backend/member/controller/MemberController.java
  src/main/java/fisa/woorizip/backend/member/controller/auth/AuthArgumentResolver.java
  src/main/java/fisa/woorizip/backend/member/controller/auth/AuthController.java
  src/main/java/fisa/woorizip/backend/member/controller/auth/AuthInterceptor.java
  src/main/java/fisa/woorizip/backend/member/controller/auth/CookieProvider.java
  src/main/java/fisa/woorizip/backend/member/controller/auth/Login.java
  src/main/java/fisa/woorizip/backend/member/controller/auth/MemberIdentity.java
  src/main/java/fisa/woorizip/backend/member/controller/auth/VerifiedMember.java
  src/main/java/fisa/woorizip/backend/member/domain/RefreshToken.java
  src/main/java/fisa/woorizip/backend/member/domain/Role.java
  src/main/java/fisa/woorizip/backend/member/dto/request/SignInRequest.java
  src/main/java/fisa/woorizip/backend/member/dto/request/SignUpRequest.java
  src/main/java/fisa/woorizip/backend/member/dto/response/SignInResponse.java
  src/main/java/fisa/woorizip/backend/member/dto/result/RefreshTokenResult.java
  src/main/java/fisa/woorizip/backend/member/dto/result/SignInResult.java
  src/main/java/fisa/woorizip/backend/member/repository/MemberRepository.java
  src/main/java/fisa/woorizip/backend/member/repository/RefreshTokenRepository.java
  src/main/java/fisa/woorizip/backend/member/service/MemberService.java
  src/main/java/fisa/woorizip/backend/member/service/MemberServiceImpl.java
  src/main/java/fisa/woorizip/backend/member/service/auth/AuthService.java
  src/main/java/fisa/woorizip/backend/member/service/auth/AuthServiceImpl.java
  src/main/java/fisa/woorizip/backend/member/service/auth/JwtTokenProvider.java
  src/main/resources/application-dev.yml
  src/main/resources/db/migration/V1__init.sql
  src/test/java/fisa/woorizip/backend/member/repository/MemberRepositoryTest.java
  src/test/java/fisa/woorizip/backend/member/service/auth/JwtTokenProviderTest.java
  src/test/java/fisa/woorizip/backend/support/ControllerTest.java
  src/test/java/fisa/woorizip/backend/support/fixture/MemberFixture.java
Labels: ✨ Feature

#20 [FEAT] 대출상세보기기능 #14
  src/main/java/fisa/woorizip/backend/loangoods/LoanGoodsErrorCode.java
  src/main/java/fisa/woorizip/backend/loangoods/controller/LoanGoodsController.java
  src/main/java/fisa/woorizip/backend/loangoods/dto/response/ShowLoanGoodsDetailsResponse.java
  src/main/java/fisa/woorizip/backend/loangoods/repository/LoanGoodsRepository.java
  src/main/java/fisa/woorizip/backend/loangoods/service/LoanGoodsService.java
  src/main/java/fisa/woorizip/backend/loangoods/service/LoanGoodsServiceImpl.java
  src/main/java/fisa/woorizip/backend/member/service/MemberService.java
  src/test/java/fisa/woorizip/backend/loangoods/controller/LoanGoodsControllerTest.java
  src/test/java/fisa/woorizip/backend/loangoods/repository/LoanGoodsRepositoryTest.java
  src/test/java/fisa/woorizip/backend/loangoods/service/LoanGoodsServiceTest.java
  src/test/java/fisa/woorizip/backend/support/fixture/HouseFixture.java
Labels: ✨ Feature

#21 [FEAT] 집 상세 조회 기능 #10
  src/main/java/fisa/woorizip/backend/house/HouseErrorCode.java
  src/main/java/fisa/woorizip/backend/house/controller/HouseController.java
  src/main/java/fisa/woorizip/backend/house/dto/response/HouseDetailResponse.java
  src/main/java/fisa/woorizip/backend/house/service/HouseService.java
  src/main/java/fisa/woorizip/backend/house/service/HouseServiceImpl.java
  src/main/java/fisa/woorizip/backend/houseimage/HouseImageErrorCode.java
  src/main/java/fisa/woorizip/backend/houseimage/repository/HouseImageRepository.java
  src/test/java/fisa/woorizip/backend/house/controller/HouseControllerMockMvcTest.java
  src/test/java/fisa/woorizip/backend/house/repository/HouseRepositoryTest.java
  src/test/java/fisa/woorizip/backend/house/service/HouseServiceTest.java
  src/test/java/fisa/woorizip/backend/houseimage/repository/HouseImageRepositoryTest.java
  src/test/java/fisa/woorizip/backend/support/fixture/HouseImageFixture.java
Labels: ✨ Feature

#31 [FEAT] 대출 체크리스트 기능 #23
  src/main/java/fisa/woorizip/backend/loanchecklist/controller/LoanCheckListController.java
  src/main/java/fisa/woorizip/backend/loanchecklist/domain/LoanCheckList.java
  src/main/java/fisa/woorizip/backend/loanchecklist/dto/response/ShowLoanCheckListResponse.java
  src/main/java/fisa/woorizip/backend/loanchecklist/repository/LoanCheckListRepository.java
  src/main/java/fisa/woorizip/backend/loanchecklist/service/LoanCheckListService.java
  src/main/java/fisa/woorizip/backend/loanchecklist/service/LoanCheckListServiceImpl.java
  src/main/resources/db/migration/V1__init.sql
  src/test/java/fisa/woorizip/backend/loanchecklist/controller/LoanCheckListControllerTest.java
  src/test/java/fisa/woorizip/backend/loanchecklist/repository/LoanCheckListRepositoryTest.java
  src/test/java/fisa/woorizip/backend/loanchecklist/service/LoanCheckListServiceTest.java
  src/test/java/fisa/woorizip/backend/support/fixture/LoanCheckListFixture.java
Labels: ✨ Feature

#29 [FEAT] 토큰 재발급 기능, EnumScanner 추가
  build.gradle
  src/main/java/fisa/woorizip/backend/common/exception/EnumScanner.java
  src/main/java/fisa/woorizip/backend/common/exception/GlobalExceptionHandler.java
  src/main/java/fisa/woorizip/backend/common/exception/errorcode/CommonErrorCode.java
  src/main/java/fisa/woorizip/backend/member/AuthErrorCode.java
  src/main/java/fisa/woorizip/backend/member/controller/auth/AuthController.java
  src/main/java/fisa/woorizip/backend/member/controller/auth/AuthInterceptor.java
  src/main/java/fisa/woorizip/backend/member/service/auth/AuthService.java
  src/main/java/fisa/woorizip/backend/member/service/auth/AuthServiceImpl.java
  src/main/java/fisa/woorizip/backend/member/service/auth/JwtTokenProvider.java
  src/test/java/fisa/woorizip/backend/common/exception/EnumScannerTest.java
Labels: ✨ Feature

#34 [FIX] 지도 API 업데이트
  build.gradle
  src/main/java/fisa/woorizip/backend/house/controller/HouseController.java
  src/main/java/fisa/woorizip/backend/house/domain/House.java
  src/main/java/fisa/woorizip/backend/house/dto/request/MapFilterRequest.java
  src/main/java/fisa/woorizip/backend/house/dto/response/HouseDetailResponse.java
  src/main/java/fisa/woorizip/backend/house/dto/result/HouseContentResult.java
  src/main/java/fisa/woorizip/backend/house/dto/result/HouseCountResult.java
  src/main/java/fisa/woorizip/backend/house/dto/result/HouseResult.java
  src/main/java/fisa/woorizip/backend/house/repository/HouseCustomRepository.java
  src/main/java/fisa/woorizip/backend/house/repository/HouseCustomRepositoryImpl.java
  src/main/java/fisa/woorizip/backend/house/repository/HouseRepository.java
  src/main/java/fisa/woorizip/backend/house/repository/HouseRepositoryCustom.java
  src/main/java/fisa/woorizip/backend/house/repository/HouseRepositoryCustomImpl.java
  src/main/java/fisa/woorizip/backend/house/service/HouseService.java
  src/main/java/fisa/woorizip/backend/house/service/HouseServiceImpl.java
  src/main/resources/db/migration/V1__init.sql
  src/test/java/fisa/woorizip/backend/house/controller/HouseControllerTest.java
  src/test/java/fisa/woorizip/backend/house/repository/HouseRepositoryTest.java
  src/test/java/fisa/woorizip/backend/house/service/HouseServiceTest.java
  src/test/java/fisa/woorizip/backend/support/fixture/HouseFixture.java
Labels: ✨ Feature, 🐞 Bug, ♻️ Refactor

#39 [FEAT] 우리은행 데이터 분석 및 소비 패턴 분석 데이터 DB로 로드
  .gitignore
  src/main/java/fisa/woorizip/backend/consumptionanalysis/domain/ConsumptionAnalysis.java
  src/main/resources/db/migration/V1__init.sql
  src/main/resources/db/migration/V2__load_csv.sql
Labels: ✨ Feature, ⚙ Setting

#38 [FEAT] 대출 추천 기능 #32
  src/main/java/fisa/woorizip/backend/loangoods/controller/LoanGoodsController.java
  src/main/java/fisa/woorizip/backend/loangoods/domain/LoanGoods.java
  src/main/java/fisa/woorizip/backend/loangoods/repository/LoanGoodsRepository.java
  src/main/java/fisa/woorizip/backend/loangoods/service/LoanGoodsService.java
  src/main/java/fisa/woorizip/backend/loangoods/service/LoanGoodsServiceImpl.java
  src/main/java/fisa/woorizip/backend/member/controller/MemberController.java
  src/main/java/fisa/woorizip/backend/member/domain/Member.java
  src/main/java/fisa/woorizip/backend/member/dto/request/SignUpRequest.java
  src/main/resources/db/migration/V1__init.sql
  src/test/java/fisa/woorizip/backend/loangoods/controller/LoanGoodsControllerTest.java
  src/test/java/fisa/woorizip/backend/loangoods/repository/LoanGoodsRepositoryTest.java
  src/test/java/fisa/woorizip/backend/loangoods/service/LoanGoodsServiceTest.java
  src/test/java/fisa/woorizip/backend/support/fixture/LoanGoodsFixture.java
  src/test/java/fisa/woorizip/backend/support/fixture/MemberFixture.java
Labels: ✨ Feature

#40 [FEAT] 북마크 목록 추가 기능 #28
  src/main/java/fisa/woorizip/backend/bookmark/BookmarkErrorCode.java
  src/main/java/fisa/woorizip/backend/bookmark/controller/BookmarkController.java
  src/main/java/fisa/woorizip/backend/bookmark/domain/Bookmark.java
  src/main/java/fisa/woorizip/backend/bookmark/dto/request/BookmarkRequest.java
  src/main/java/fisa/woorizip/backend/bookmark/repository/BookmarkRepository.java
  src/main/java/fisa/woorizip/backend/bookmark/service/BookmarkService.java
  src/main/java/fisa/woorizip/backend/bookmark/service/BookmarkServiceImpl.java
  src/main/resources/db/migration/V1__init.sql
  src/test/java/fisa/woorizip/backend/bookmark/controller/BookmarkControllerTest.java
  src/test/java/fisa/woorizip/backend/bookmark/service/BookmarkServiceTest.java
Labels: ✨ Feature

#47 [FEAT] 소비 패턴 분석 결과 조회 api
  src/main/java/fisa/woorizip/backend/bookmark/dto/request/BookmarkRequest.java
  src/main/java/fisa/woorizip/backend/consumptionanalysis/repository/ConsumptionAnalysisRepository.java
  src/main/java/fisa/woorizip/backend/facility/domain/Category.java
  src/main/java/fisa/woorizip/backend/member/MemberErrorCode.java
  src/main/java/fisa/woorizip/backend/member/domain/EarningsType.java
  src/main/java/fisa/woorizip/backend/member/domain/Gender.java
  src/main/java/fisa/woorizip/backend/member/domain/LifeStage.java
  src/main/java/fisa/woorizip/backend/member/domain/Member.java
  src/main/java/fisa/woorizip/backend/member/domain/Membership.java
  src/main/java/fisa/woorizip/backend/member/dto/request/SignUpRequest.java
  src/main/java/fisa/woorizip/backend/memberconsumption/MemberConsumptionErrorCode.java
  src/main/java/fisa/woorizip/backend/memberconsumption/controller/MemberConsumptionController.java
  src/main/java/fisa/woorizip/backend/memberconsumption/domain/MemberConsumption.java
  src/main/java/fisa/woorizip/backend/memberconsumption/dto/Age.java
  src/main/java/fisa/woorizip/backend/memberconsumption/dto/response/CategoryResponse.java
  src/main/java/fisa/woorizip/backend/memberconsumption/dto/response/ConsumptionAnalysisResponse.java
  src/main/java/fisa/woorizip/backend/memberconsumption/dto/response/ConsumptionResponse.java
  src/main/java/fisa/woorizip/backend/memberconsumption/repository/MemberConsumptionRepository.java
  src/main/java/fisa/woorizip/backend/memberconsumption/service/MemberConsumptionService.java
  src/main/java/fisa/woorizip/backend/memberconsumption/service/MemberConsumptionServiceImpl.java
  src/main/resources/db/migration/V1__init.sql
  src/test/java/fisa/woorizip/backend/common/exception/EnumScannerTest.java
  src/test/java/fisa/woorizip/backend/house/controller/HouseControllerTest.java
  src/test/java/fisa/woorizip/backend/memberconsumption/controller/MemberConsumptionControllerTest.java
  src/test/java/fisa/woorizip/backend/memberconsumption/service/MemberConsumptionServiceTest.java
  src/test/java/fisa/woorizip/backend/support/fixture/ConsumptionAnalysisFixture.java
  src/test/java/fisa/woorizip/backend/support/fixture/MemberConsumptionFixture.java
  src/test/java/fisa/woorizip/backend/support/fixture/MemberFixture.java
Labels: ✨ Feature

#46 [Feat] 북마크 삭제 기능 #45
  src/main/java/fisa/woorizip/backend/bookmark/BookmarkErrorCode.java
  src/main/java/fisa/woorizip/backend/bookmark/controller/BookmarkController.java
  src/main/java/fisa/woorizip/backend/bookmark/dto/request/BookmarkRequest.java
  src/main/java/fisa/woorizip/backend/bookmark/repository/BookmarkRepository.java
  src/main/java/fisa/woorizip/backend/bookmark/service/BookmarkService.java
  src/main/java/fisa/woorizip/backend/bookmark/service/BookmarkServiceImpl.java
  src/main/java/fisa/woorizip/backend/member/controller/auth/MemberIdentity.java
  src/test/java/fisa/woorizip/backend/bookmark/controller/BookmarkControllerTest.java
  src/test/java/fisa/woorizip/backend/bookmark/service/BookmarkServiceTest.java
  src/test/java/fisa/woorizip/backend/support/fixture/BookmarkFixture.java
Labels: ✨ Feature

#44 [FEAT] 북마크 목록 조회 API #33
  src/main/java/fisa/woorizip/backend/bookmark/BookmarkErrorCode.java
  src/main/java/fisa/woorizip/backend/bookmark/controller/BookmarkController.java
  src/main/java/fisa/woorizip/backend/bookmark/domain/Bookmark.java
  src/main/java/fisa/woorizip/backend/bookmark/dto/response/BookmarkListResponse.java
  src/main/java/fisa/woorizip/backend/bookmark/dto/response/ShowBookmarksResponse.java
  src/main/java/fisa/woorizip/backend/bookmark/repository/BookmarkRepository.java
  src/main/java/fisa/woorizip/backend/bookmark/service/BookmarkService.java
  src/main/java/fisa/woorizip/backend/bookmark/service/BookmarkServiceImpl.java
  src/test/java/fisa/woorizip/backend/bookmark/controller/BookmarkControllerTest.java
  src/test/java/fisa/woorizip/backend/bookmark/repository/BookmarkRepositoryTest.java
  src/test/java/fisa/woorizip/backend/bookmark/service/BookmarkServiceTest.java
Labels: ✨ Feature

#49 [FEAT] 권한 별 회원가입 기능 및 은행 서버와 통신
  src/main/java/fisa/woorizip/backend/agent/Agent.java
  src/main/java/fisa/woorizip/backend/agent/AgentRepository.java
  src/main/java/fisa/woorizip/backend/member/AuthErrorCode.java
  src/main/java/fisa/woorizip/backend/member/MemberErrorCode.java
  src/main/java/fisa/woorizip/backend/member/controller/MemberController.java
  src/main/java/fisa/woorizip/backend/member/controller/auth/AuthController.java
  src/main/java/fisa/woorizip/backend/member/controller/auth/AuthInterceptor.java
  src/main/java/fisa/woorizip/backend/member/domain/Gender.java
  src/main/java/fisa/woorizip/backend/member/domain/LifeStage.java
  src/main/java/fisa/woorizip/backend/member/domain/Member.java
  src/main/java/fisa/woorizip/backend/member/domain/Membership.java
  src/main/java/fisa/woorizip/backend/member/domain/Role.java
  src/main/java/fisa/woorizip/backend/member/domain/Status.java
  src/main/java/fisa/woorizip/backend/member/dto/request/SignUpRequest.java
  src/main/java/fisa/woorizip/backend/member/dto/response/SignInResponse.java
  src/main/java/fisa/woorizip/backend/member/repository/MemberRepository.java
  src/main/java/fisa/woorizip/backend/member/service/MemberServiceImpl.java
  src/main/java/fisa/woorizip/backend/member/service/auth/AuthService.java
  src/main/java/fisa/woorizip/backend/member/service/auth/AuthServiceImpl.java
  src/main/java/fisa/woorizip/backend/member/service/auth/GetMemberDataResponse.java
  src/main/java/fisa/woorizip/backend/member/service/auth/GetWooriBankTokenRequest.java
  src/main/java/fisa/woorizip/backend/member/service/auth/GetWooriBankTokenResponse.java
  src/main/java/fisa/woorizip/backend/member/service/auth/ShowMemberDataResponse.java
  src/main/java/fisa/woorizip/backend/member/service/auth/SpendingHistoryResponse.java
  src/main/java/fisa/woorizip/backend/member/service/auth/WooriBankOauth.java
  src/main/java/fisa/woorizip/backend/memberconsumption/domain/MemberConsumption.java
  src/main/resources/db/migration/V1__init.sql
Labels: ✨ Feature

#51 [SETTING] 중개업자 데이터 로드
  .gitignore
  src/main/resources/db/migration/V1__init.sql
Labels: ⚙ Setting

#54 [FEAT] 데이터베이스 수정
  src/main/java/fisa/woorizip/backend/loanchecklist/LoanCheckListErrorCode.java
  src/main/java/fisa/woorizip/backend/loanchecklist/controller/LoanCheckListController.java
  src/main/java/fisa/woorizip/backend/loanchecklist/domain/LoanCheckList.java
  src/main/java/fisa/woorizip/backend/loanchecklist/domain/MarriageStatus.java
  src/main/java/fisa/woorizip/backend/loanchecklist/domain/WorkStatus.java
  src/main/java/fisa/woorizip/backend/loanchecklist/domain/WorkTerm.java
  src/main/java/fisa/woorizip/backend/loanchecklist/dto/response/ShowLoanCheckListResponse.java
  src/main/java/fisa/woorizip/backend/loanchecklist/repository/LoanCheckListRepository.java
  src/main/java/fisa/woorizip/backend/loanchecklist/repository/LoanChecklistRepository.java
  src/main/java/fisa/woorizip/backend/loanchecklist/service/LoanCheckListService.java
  src/main/java/fisa/woorizip/backend/loanchecklist/service/LoanCheckListServiceImpl.java
  src/main/java/fisa/woorizip/backend/loangoods/LoanGoodsErrorCode.java
  src/main/java/fisa/woorizip/backend/loangoods/controller/LoanGoodsController.java
  src/main/java/fisa/woorizip/backend/loangoods/domain/LoanGoods.java
  src/main/java/fisa/woorizip/backend/loangoods/domain/LoanGoodsType.java
  src/main/java/fisa/woorizip/backend/loangoods/domain/LoanType.java
  src/main/java/fisa/woorizip/backend/loangoods/dto/response/ShowLoanGoodsDetailsResponse.java
  src/main/java/fisa/woorizip/backend/loangoods/repository/LoanGoodsRepository.java
  src/main/java/fisa/woorizip/backend/loangoods/service/LoanGoodsService.java
  src/main/java/fisa/woorizip/backend/loangoods/service/LoanGoodsServiceImpl.java
  src/main/java/fisa/woorizip/backend/member/domain/Member.java
  src/main/java/fisa/woorizip/backend/member/service/auth/GetMemberDataResponse.java
  src/main/java/fisa/woorizip/backend/rate/domain/Rate.java
  src/main/java/fisa/woorizip/backend/rate/domain/RateType.java
  src/main/java/fisa/woorizip/backend/rate/repository/RateRepository.java
  src/main/resources/db/migration/V1__init.sql
Labels: ✨ Feature

#56 [FEAT] 공통 Response 반환하는 기능 추가
  src/main/java/fisa/woorizip/backend/common/ApiResponse.java
  src/main/java/fisa/woorizip/backend/common/ApiResponseHandler.java
  src/main/java/fisa/woorizip/backend/common/exception/GlobalExceptionHandler.java
  src/main/java/fisa/woorizip/backend/member/controller/auth/AuthArgumentResolver.java
  src/main/java/fisa/woorizip/backend/member/domain/Member.java
Labels: ✨ Feature

#60 [FEAT] 관리자 권한 승인/취소 기능
  src/main/java/fisa/woorizip/backend/common/exception/GlobalExceptionHandler.java
  src/main/java/fisa/woorizip/backend/common/exception/WoorizipDetailException.java
  src/main/java/fisa/woorizip/backend/member/MemberErrorCode.java
  src/main/java/fisa/woorizip/backend/member/controller/MemberController.java
  src/main/java/fisa/woorizip/backend/member/domain/Member.java
  src/main/java/fisa/woorizip/backend/member/domain/Status.java
  src/main/java/fisa/woorizip/backend/member/dto/request/ApprovalRequest.java
  src/main/java/fisa/woorizip/backend/member/dto/request/RevokeApprovalRequest.java
  src/main/java/fisa/woorizip/backend/member/repository/MemberRepository.java
  src/main/java/fisa/woorizip/backend/member/service/MemberService.java
  src/main/java/fisa/woorizip/backend/member/service/MemberServiceImpl.java
  src/test/java/fisa/woorizip/backend/member/service/MemberServiceTest.java
  src/test/java/fisa/woorizip/backend/support/fixture/MemberFixture.java
Labels: ✨ Feature

#61 [FEAT] 회원 정보 조회 api
  src/main/java/fisa/woorizip/backend/common/PageArgumentResolver.java
  src/main/java/fisa/woorizip/backend/member/controller/MemberController.java
  src/main/java/fisa/woorizip/backend/member/controller/auth/AuthInterceptor.java
  src/main/java/fisa/woorizip/backend/member/controller/auth/Login.java
  src/main/java/fisa/woorizip/backend/member/domain/Membership.java
  src/main/java/fisa/woorizip/backend/member/dto/response/MemberInfoResponse.java
  src/main/java/fisa/woorizip/backend/member/service/MemberService.java
  src/main/java/fisa/woorizip/backend/member/service/MemberServiceImpl.java
  src/main/java/fisa/woorizip/backend/recentlyloangoods/controller/RecentlyLoanGoodsController.java
  src/test/java/fisa/woorizip/backend/member/service/MemberServiceTest.java
Labels: ✨ Feature
